max_width = 100
tab_spaces = 4
newline_style = "Unix" 

fn_call_width = 80
fn_params_layout = "Tall"

struct_field_align_threshold = 20
enum_discrim_align_threshold = 20

imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true

edition = "2021"
use_small_heuristics = "Max"     
